CREATE TABLE Students(
StudentID INT NOT NULL,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE Exams(
ExamID INT NOT NULL,
[Name] NVARCHAR(50) NOT NULL
)

CREATE TABLE StudentsExams(
StudentID INT NOT NULL,
ExamID INT NOT NULL,
)

ALTER TABLE Students
	ADD CONSTRAINT PK_Students
		PRIMARY KEY(StudentID)

ALTER TABLE Exams
	ADD CONSTRAINT PK_Exams
	PRIMARY KEY(ExamID)

ALTER TABLE StudentsExams
	ADD CONSTRAINT PK_StudentsExams
	PRIMARY KEY (StudentID, ExamID)

ALTER TABLE StudentsExams
	ADD CONSTRAINT FK_StudentsExams_Students
	FOREIGN KEY(StudentID)
	REFERENCES Students(StudentID)

ALTER TABLE StudentsExams
	ADD CONSTRAINT FK_StudentsExams_Exams
	FOREIGN KEY(ExamID)
	REFERENCES Exams(ExamID)