--CREATE DATABASE Softuni
--Use Softuni
CREATE TABLE Towns(
Id INT PRIMARY KEY IDENTITY NOT NULl,
[Name] VARCHAR(MAX) NOT NULL
)

CREATE TABLE Addresses(
Id INT PRIMARY KEY IDENTITY NOT NULL,
AddressText NVARCHAR(50) NOT NULL,
TownId INT FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) NOT NULl
)

CREATE TABLE Employees(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(20) NOT NULL,
MiddleName VARCHAR(20),
LastName VARCHAR(20) NOT NULL,
JobTitle NVARCHAR(MAX) NOT NULL,
DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
HireDate DATETIME NOT NULL,
Salary DECIMAL(15, 2) NOT NULL,
AddressId INT FOREIGN KEY REFERENCES Addresses(Id)
)